sudo: required
services:
  - docker

before_install:
  - docker build -t zhaoshuosve/docker-react -f Dockerfile.dev .


scripts:
  - docker run -e CI=tru zhaoshuosve/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "datjan-react-docker"
  env: "DatjanReactDocker-env"
  bucket_name: "datjan-react-docker"
  bucket_path: "datjan-docker-react.zip"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
